---
- name: Configure Database Server for WordPress
  hosts: dbservers
  become: yes
  roles:
    - db

- name: Configure Web Server for WordPress
  hosts: webservers
  become: yes
  roles:
    - web

- name: Deploy WordPress Application
  hosts: webservers
  become: yes
  roles:
    - wordpress