[webservers]
node-1 ansible_host=192.168.88.50
[dbservers]
node-2 ansible_host=192.168.88.60
[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
ansible_shell_type=sh
