---
nginx_server_name: "192.168.88.50" 
wp_install_dir: "/var/www/localhost/htdocs/wordpress"

wp_version: "6.4.3" 
wp_archive_url: "https://wordpress.org/wordpress-{{ wp_version }}.tar.gz"

# Current PHP Version used in Alpine 
php_version: "85"
